### PR TITLE
Monthly report draft

### PR DESCRIPTION
**Pull request by manedev79**
WIP - Needs to be improved.

### CODE REVIEW

**Comment by manedev79** [comment]
First draft uses a redundant field 'month' in the WorkingDay entity. Better approach would be to use the already existing 'day' property and query the whole range of the month in days, i.e. all working days between first day of month and last day of month.
Could be we face issues here because we mix LocalDate and Instant.

**Comment by manedev79** [comment]
Will look for a solution in my next time slot :)

**Comment by JanLoebel** [comment]
I've created an extra branch to show you what I would have done here :)
Checkout: https://github.com/manedev79/timesheet/pull/6

**Comment by manedev79** [comment]
Will go for #6. Had planned almost the same.

**Pull request closed without merging**
